#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adopcion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDAdopcion")]
	public partial class AdopcionBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTAdministrador(TAdministrador instance);
    partial void UpdateTAdministrador(TAdministrador instance);
    partial void DeleteTAdministrador(TAdministrador instance);
    partial void InsertTAdoptante(TAdoptante instance);
    partial void UpdateTAdoptante(TAdoptante instance);
    partial void DeleteTAdoptante(TAdoptante instance);
    partial void InsertTMascota(TMascota instance);
    partial void UpdateTMascota(TMascota instance);
    partial void DeleteTMascota(TMascota instance);
    partial void InsertTorganizacion(Torganizacion instance);
    partial void UpdateTorganizacion(Torganizacion instance);
    partial void DeleteTorganizacion(Torganizacion instance);
    partial void InsertTSolicitud(TSolicitud instance);
    partial void UpdateTSolicitud(TSolicitud instance);
    partial void DeleteTSolicitud(TSolicitud instance);
    partial void InsertTUsuario(TUsuario instance);
    partial void UpdateTUsuario(TUsuario instance);
    partial void DeleteTUsuario(TUsuario instance);
    #endregion
		
		public AdopcionBDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDAdopcionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdopcionBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdopcionBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdopcionBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdopcionBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TAdministrador> TAdministrador
		{
			get
			{
				return this.GetTable<TAdministrador>();
			}
		}
		
		public System.Data.Linq.Table<TAdoptante> TAdoptante
		{
			get
			{
				return this.GetTable<TAdoptante>();
			}
		}
		
		public System.Data.Linq.Table<TMascota> TMascota
		{
			get
			{
				return this.GetTable<TMascota>();
			}
		}
		
		public System.Data.Linq.Table<Torganizacion> Torganizacion
		{
			get
			{
				return this.GetTable<Torganizacion>();
			}
		}
		
		public System.Data.Linq.Table<TSolicitud> TSolicitud
		{
			get
			{
				return this.GetTable<TSolicitud>();
			}
		}
		
		public System.Data.Linq.Table<TUsuario> TUsuario
		{
			get
			{
				return this.GetTable<TUsuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarMascota")]
		public ISingleResult<spActualizarMascotaResult> spActualizarMascota([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMascota", DbType="VarChar(5)")] string idMascota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sexo", DbType="VarChar(50)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Raza", DbType="VarChar(50)")] string raza, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoMascota", DbType="VarChar(50)")] string tipoMascota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Imagen", DbType="VarChar(50)")] string imagen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tamaño", DbType="VarChar(50)")] string tamaño, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacAprox", DbType="DateTime")] System.Nullable<System.DateTime> fechaNacAprox, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMascota, estado, nombre, sexo, raza, tipoMascota, imagen, tamaño, fechaNacAprox, descripcion);
			return ((ISingleResult<spActualizarMascotaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarOrganizacion")]
		public ISingleResult<spActualizarOrganizacionResult> spActualizarOrganizacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DireccionUBI", DbType="VarChar(50)")] string direccionUBI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Localidad", DbType="VarChar(50)")] string localidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nroContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoElectronico", DbType="VarChar(50)")] string correoElectronico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, direccionUBI, localidad, nroContacto, correoElectronico);
			return ((ISingleResult<spActualizarOrganizacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarProducto")]
		public ISingleResult<spActualizarProductoResult> spActualizarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nacimiento", DbType="DateTime")] System.Nullable<System.DateTime> fecha_Nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDocuemnto", DbType="VarChar(50)")] string tipoDocuemnto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroDocumento", DbType="VarChar(10)")] string nroDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string nroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado_civil", DbType="VarChar(50)")] string estado_civil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ocupacion", DbType="VarChar(50)")] string ocupacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, nombre, apellido, fecha_Nacimiento, tipoDocuemnto, nroDocumento, nroCelular, direccion, estado_civil, ocupacion);
			return ((ISingleResult<spActualizarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarAdministrador")]
		public ISingleResult<spAgregarAdministradorResult> spAgregarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroCelular", DbType="VarChar(9)")] string nroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDocumento", DbType="VarChar(8)")] string tipoDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nroDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string idOrganizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(20)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, direccion, nroCelular, tipoDocumento, nroDocumento, usuario, idOrganizacion, contrasena);
			return ((ISingleResult<spAgregarAdministradorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarAdoptante")]
		public ISingleResult<spAgregarAdoptanteResult> spAgregarAdoptante([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(50)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nacimiento", DbType="DateTime")] System.Nullable<System.DateTime> fecha_Nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDocuemnto", DbType="VarChar(50)")] string tipoDocuemnto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string nroDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string nroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado_civil", DbType="VarChar(50)")] string estado_civil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ocupacion", DbType="VarChar(50)")] string ocupacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(20)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, nombre, apellido, fecha_Nacimiento, tipoDocuemnto, nroDocumento, nroCelular, direccion, estado_civil, ocupacion, contrasena);
			return ((ISingleResult<spAgregarAdoptanteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarMascota")]
		public ISingleResult<spAgregarMascotaResult> spAgregarMascota([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sexo", DbType="VarChar(50)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Raza", DbType="VarChar(50)")] string raza, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoMascota", DbType="VarChar(50)")] string tipoMascota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Imagen", DbType="VarChar(MAX)")] string imagen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tamaño", DbType="VarChar(50)")] string tamaño, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNacAprox", DbType="DateTime")] System.Nullable<System.DateTime> fechaNacAprox, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(20)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, nombre, sexo, raza, tipoMascota, imagen, tamaño, fechaNacAprox, descripcion);
			return ((ISingleResult<spAgregarMascotaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarOrganizacion")]
		public ISingleResult<spAgregarOrganizacionResult> spAgregarOrganizacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DireccionUBI", DbType="VarChar(50)")] string direccionUBI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Localidad", DbType="VarChar(50)")] string localidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nroContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoElectronico", DbType="VarChar(50)")] string correoElectronico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, direccionUBI, localidad, nroContacto, correoElectronico);
			return ((ISingleResult<spAgregarOrganizacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarSolicitud")]
		public ISingleResult<spAgregarSolicitudResult> spAgregarSolicitud([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdOrganizacion", DbType="VarChar(5)")] string idOrganizacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMascota", DbType="VarChar(5)")] string idMascota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAdoptante", DbType="VarChar(5)")] string idAdoptante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaSolicitud", DbType="DateTime")] System.Nullable<System.DateTime> fechaSolicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrganizacion, idMascota, idAdoptante, estado, fechaSolicitud, descripcion);
			return ((ISingleResult<spAgregarSolicitudResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCambiarEstadoSolicitud")]
		public ISingleResult<spCambiarEstadoSolicitudResult> spCambiarEstadoSolicitud([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSolicitud", DbType="VarChar(5)")] string idSolicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoEstado", DbType="VarChar(50)")] string nuevoEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSolicitud, nuevoEstado);
			return ((ISingleResult<spCambiarEstadoSolicitudResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEditarAdministrador")]
		public ISingleResult<spEditarAdministradorResult> spEditarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="VarChar(100)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDocumento", DbType="VarChar(8)")] string tipoDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroCelular", DbType="VarChar(9)")] string nroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, apellido, tipoDocumento, nroCelular, direccion, usuario);
			return ((ISingleResult<spEditarAdministradorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarAdministrador")]
		public ISingleResult<spEliminarAdministradorResult> spEliminarAdministrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario);
			return ((ISingleResult<spEliminarAdministradorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarAdoptante")]
		public ISingleResult<spEliminarAdoptanteResult> spEliminarAdoptante([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAdoptante", DbType="VarChar(4)")] string idAdoptante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAdoptante, usuario);
			return ((ISingleResult<spEliminarAdoptanteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarMascota")]
		public ISingleResult<spEliminarMascotaResult> spEliminarMascota([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMascota", DbType="Int")] System.Nullable<int> idMascota)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMascota);
			return ((ISingleResult<spEliminarMascotaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarOrganizacion")]
		public ISingleResult<spEliminarOrganizacionResult> spEliminarOrganizacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo);
			return ((ISingleResult<spEliminarOrganizacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarAdministrador")]
		public ISingleResult<spListarAdministradorResult> spListarAdministrador()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarAdministradorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarAdoptante")]
		public ISingleResult<spListarAdoptanteResult> spListarAdoptante()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListarAdoptanteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLoginUsuario")]
		public ISingleResult<spLoginUsuarioResult> spLoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
			return ((ISingleResult<spLoginUsuarioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAdministrador")]
	public partial class TAdministrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAdministrador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _nroCelular;
		
		private string _TipoDocumento;
		
		private string _nroDocumento;
		
		private string _Usuario;
		
		private System.Nullable<int> _IdOrganizacion;
		
		private EntityRef<Torganizacion> _Torganizacion;
		
		private EntityRef<TUsuario> _TUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAdministradorChanging(int value);
    partial void OnIdAdministradorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnnroCelularChanging(string value);
    partial void OnnroCelularChanged();
    partial void OnTipoDocumentoChanging(string value);
    partial void OnTipoDocumentoChanged();
    partial void OnnroDocumentoChanging(string value);
    partial void OnnroDocumentoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnIdOrganizacionChanging(System.Nullable<int> value);
    partial void OnIdOrganizacionChanged();
    #endregion
		
		public TAdministrador()
		{
			this._Torganizacion = default(EntityRef<Torganizacion>);
			this._TUsuario = default(EntityRef<TUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdministrador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAdministrador
		{
			get
			{
				return this._IdAdministrador;
			}
			set
			{
				if ((this._IdAdministrador != value))
				{
					this.OnIdAdministradorChanging(value);
					this.SendPropertyChanging();
					this._IdAdministrador = value;
					this.SendPropertyChanged("IdAdministrador");
					this.OnIdAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroCelular", DbType="VarChar(9)")]
		public string nroCelular
		{
			get
			{
				return this._nroCelular;
			}
			set
			{
				if ((this._nroCelular != value))
				{
					this.OnnroCelularChanging(value);
					this.SendPropertyChanging();
					this._nroCelular = value;
					this.SendPropertyChanged("nroCelular");
					this.OnnroCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(50)")]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this.OnTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumento = value;
					this.SendPropertyChanged("TipoDocumento");
					this.OnTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDocumento", DbType="VarChar(50)")]
		public string nroDocumento
		{
			get
			{
				return this._nroDocumento;
			}
			set
			{
				if ((this._nroDocumento != value))
				{
					this.OnnroDocumentoChanging(value);
					this.SendPropertyChanging();
					this._nroDocumento = value;
					this.SendPropertyChanged("nroDocumento");
					this.OnnroDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					if (this._TUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrganizacion", DbType="Int")]
		public System.Nullable<int> IdOrganizacion
		{
			get
			{
				return this._IdOrganizacion;
			}
			set
			{
				if ((this._IdOrganizacion != value))
				{
					if (this._Torganizacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdOrganizacionChanging(value);
					this.SendPropertyChanging();
					this._IdOrganizacion = value;
					this.SendPropertyChanged("IdOrganizacion");
					this.OnIdOrganizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Torganizacion_TAdministrador", Storage="_Torganizacion", ThisKey="IdOrganizacion", OtherKey="IdOrganizacion", IsForeignKey=true)]
		public Torganizacion Torganizacion
		{
			get
			{
				return this._Torganizacion.Entity;
			}
			set
			{
				Torganizacion previousValue = this._Torganizacion.Entity;
				if (((previousValue != value) 
							|| (this._Torganizacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Torganizacion.Entity = null;
						previousValue.TAdministrador.Remove(this);
					}
					this._Torganizacion.Entity = value;
					if ((value != null))
					{
						value.TAdministrador.Add(this);
						this._IdOrganizacion = value.IdOrganizacion;
					}
					else
					{
						this._IdOrganizacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Torganizacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TAdministrador", Storage="_TUsuario", ThisKey="Usuario", OtherKey="Usuario", IsForeignKey=true)]
		public TUsuario TUsuario
		{
			get
			{
				return this._TUsuario.Entity;
			}
			set
			{
				TUsuario previousValue = this._TUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUsuario.Entity = null;
						previousValue.TAdministrador.Remove(this);
					}
					this._TUsuario.Entity = value;
					if ((value != null))
					{
						value.TAdministrador.Add(this);
						this._Usuario = value.Usuario;
					}
					else
					{
						this._Usuario = default(string);
					}
					this.SendPropertyChanged("TUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAdoptante")]
	public partial class TAdoptante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAdoptante;
		
		private string _Usuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<System.DateTime> _Fecha_Nacimiento;
		
		private string _TipoDocumento;
		
		private string _nroDocumento;
		
		private string _nroCelular;
		
		private string _Direccion;
		
		private string _Estado_civil;
		
		private string _Ocupacion;
		
		private EntitySet<TSolicitud> _TSolicitud;
		
		private EntityRef<TUsuario> _TUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAdoptanteChanging(int value);
    partial void OnIdAdoptanteChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnFecha_NacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_NacimientoChanged();
    partial void OnTipoDocumentoChanging(string value);
    partial void OnTipoDocumentoChanged();
    partial void OnnroDocumentoChanging(string value);
    partial void OnnroDocumentoChanged();
    partial void OnnroCelularChanging(string value);
    partial void OnnroCelularChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnEstado_civilChanging(string value);
    partial void OnEstado_civilChanged();
    partial void OnOcupacionChanging(string value);
    partial void OnOcupacionChanged();
    #endregion
		
		public TAdoptante()
		{
			this._TSolicitud = new EntitySet<TSolicitud>(new Action<TSolicitud>(this.attach_TSolicitud), new Action<TSolicitud>(this.detach_TSolicitud));
			this._TUsuario = default(EntityRef<TUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdoptante", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAdoptante
		{
			get
			{
				return this._IdAdoptante;
			}
			set
			{
				if ((this._IdAdoptante != value))
				{
					this.OnIdAdoptanteChanging(value);
					this.SendPropertyChanging();
					this._IdAdoptante = value;
					this.SendPropertyChanged("IdAdoptante");
					this.OnIdAdoptanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					if (this._TUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this.OnFecha_NacimientoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Nacimiento = value;
					this.SendPropertyChanged("Fecha_Nacimiento");
					this.OnFecha_NacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(50)")]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this.OnTipoDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipoDocumento = value;
					this.SendPropertyChanged("TipoDocumento");
					this.OnTipoDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDocumento", DbType="VarChar(10)")]
		public string nroDocumento
		{
			get
			{
				return this._nroDocumento;
			}
			set
			{
				if ((this._nroDocumento != value))
				{
					this.OnnroDocumentoChanging(value);
					this.SendPropertyChanging();
					this._nroDocumento = value;
					this.SendPropertyChanged("nroDocumento");
					this.OnnroDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroCelular", DbType="VarChar(9)")]
		public string nroCelular
		{
			get
			{
				return this._nroCelular;
			}
			set
			{
				if ((this._nroCelular != value))
				{
					this.OnnroCelularChanging(value);
					this.SendPropertyChanging();
					this._nroCelular = value;
					this.SendPropertyChanged("nroCelular");
					this.OnnroCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_civil", DbType="VarChar(50)")]
		public string Estado_civil
		{
			get
			{
				return this._Estado_civil;
			}
			set
			{
				if ((this._Estado_civil != value))
				{
					this.OnEstado_civilChanging(value);
					this.SendPropertyChanging();
					this._Estado_civil = value;
					this.SendPropertyChanged("Estado_civil");
					this.OnEstado_civilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion", DbType="VarChar(50)")]
		public string Ocupacion
		{
			get
			{
				return this._Ocupacion;
			}
			set
			{
				if ((this._Ocupacion != value))
				{
					this.OnOcupacionChanging(value);
					this.SendPropertyChanging();
					this._Ocupacion = value;
					this.SendPropertyChanged("Ocupacion");
					this.OnOcupacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAdoptante_TSolicitud", Storage="_TSolicitud", ThisKey="IdAdoptante", OtherKey="IdAdoptante")]
		public EntitySet<TSolicitud> TSolicitud
		{
			get
			{
				return this._TSolicitud;
			}
			set
			{
				this._TSolicitud.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TAdoptante", Storage="_TUsuario", ThisKey="Usuario", OtherKey="Usuario", IsForeignKey=true)]
		public TUsuario TUsuario
		{
			get
			{
				return this._TUsuario.Entity;
			}
			set
			{
				TUsuario previousValue = this._TUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUsuario.Entity = null;
						previousValue.TAdoptante.Remove(this);
					}
					this._TUsuario.Entity = value;
					if ((value != null))
					{
						value.TAdoptante.Add(this);
						this._Usuario = value.Usuario;
					}
					else
					{
						this._Usuario = default(string);
					}
					this.SendPropertyChanged("TUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TSolicitud(TSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.TAdoptante = this;
		}
		
		private void detach_TSolicitud(TSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.TAdoptante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMascota")]
	public partial class TMascota : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdMascota;
		
		private string _Estado;
		
		private string _Nombre;
		
		private string _Sexo;
		
		private string _Raza;
		
		private string _TipoMascota;
		
		private string _Imagen;
		
		private string _Tamaño;
		
		private System.Nullable<System.DateTime> _FechaNacAprox;
		
		private string _Descripcion;
		
		private EntitySet<TSolicitud> _TSolicitud;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdMascotaChanging(int value);
    partial void OnIdMascotaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnRazaChanging(string value);
    partial void OnRazaChanged();
    partial void OnTipoMascotaChanging(string value);
    partial void OnTipoMascotaChanged();
    partial void OnImagenChanging(string value);
    partial void OnImagenChanged();
    partial void OnTamañoChanging(string value);
    partial void OnTamañoChanged();
    partial void OnFechaNacAproxChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacAproxChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TMascota()
		{
			this._TSolicitud = new EntitySet<TSolicitud>(new Action<TSolicitud>(this.attach_TSolicitud), new Action<TSolicitud>(this.detach_TSolicitud));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMascota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdMascota
		{
			get
			{
				return this._IdMascota;
			}
			set
			{
				if ((this._IdMascota != value))
				{
					this.OnIdMascotaChanging(value);
					this.SendPropertyChanging();
					this._IdMascota = value;
					this.SendPropertyChanged("IdMascota");
					this.OnIdMascotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(50)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raza", DbType="VarChar(50)")]
		public string Raza
		{
			get
			{
				return this._Raza;
			}
			set
			{
				if ((this._Raza != value))
				{
					this.OnRazaChanging(value);
					this.SendPropertyChanging();
					this._Raza = value;
					this.SendPropertyChanged("Raza");
					this.OnRazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMascota", DbType="VarChar(50)")]
		public string TipoMascota
		{
			get
			{
				return this._TipoMascota;
			}
			set
			{
				if ((this._TipoMascota != value))
				{
					this.OnTipoMascotaChanging(value);
					this.SendPropertyChanging();
					this._TipoMascota = value;
					this.SendPropertyChanged("TipoMascota");
					this.OnTipoMascotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarChar(MAX)")]
		public string Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tamaño", DbType="VarChar(50)")]
		public string Tamaño
		{
			get
			{
				return this._Tamaño;
			}
			set
			{
				if ((this._Tamaño != value))
				{
					this.OnTamañoChanging(value);
					this.SendPropertyChanging();
					this._Tamaño = value;
					this.SendPropertyChanged("Tamaño");
					this.OnTamañoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacAprox", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaNacAprox
		{
			get
			{
				return this._FechaNacAprox;
			}
			set
			{
				if ((this._FechaNacAprox != value))
				{
					this.OnFechaNacAproxChanging(value);
					this.SendPropertyChanging();
					this._FechaNacAprox = value;
					this.SendPropertyChanged("FechaNacAprox");
					this.OnFechaNacAproxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMascota_TSolicitud", Storage="_TSolicitud", ThisKey="IdMascota", OtherKey="IdMascota")]
		public EntitySet<TSolicitud> TSolicitud
		{
			get
			{
				return this._TSolicitud;
			}
			set
			{
				this._TSolicitud.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TSolicitud(TSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.TMascota = this;
		}
		
		private void detach_TSolicitud(TSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.TMascota = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Torganizacion")]
	public partial class Torganizacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdOrganizacion;
		
		private string _Nombre;
		
		private string _DireccionUBI;
		
		private string _Localidad;
		
		private string _nroContacto;
		
		private string _CorreoElectronico;
		
		private EntitySet<TAdministrador> _TAdministrador;
		
		private EntitySet<TSolicitud> _TSolicitud;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdOrganizacionChanging(int value);
    partial void OnIdOrganizacionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionUBIChanging(string value);
    partial void OnDireccionUBIChanged();
    partial void OnLocalidadChanging(string value);
    partial void OnLocalidadChanged();
    partial void OnnroContactoChanging(string value);
    partial void OnnroContactoChanged();
    partial void OnCorreoElectronicoChanging(string value);
    partial void OnCorreoElectronicoChanged();
    #endregion
		
		public Torganizacion()
		{
			this._TAdministrador = new EntitySet<TAdministrador>(new Action<TAdministrador>(this.attach_TAdministrador), new Action<TAdministrador>(this.detach_TAdministrador));
			this._TSolicitud = new EntitySet<TSolicitud>(new Action<TSolicitud>(this.attach_TSolicitud), new Action<TSolicitud>(this.detach_TSolicitud));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrganizacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdOrganizacion
		{
			get
			{
				return this._IdOrganizacion;
			}
			set
			{
				if ((this._IdOrganizacion != value))
				{
					this.OnIdOrganizacionChanging(value);
					this.SendPropertyChanging();
					this._IdOrganizacion = value;
					this.SendPropertyChanged("IdOrganizacion");
					this.OnIdOrganizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionUBI", DbType="VarChar(50)")]
		public string DireccionUBI
		{
			get
			{
				return this._DireccionUBI;
			}
			set
			{
				if ((this._DireccionUBI != value))
				{
					this.OnDireccionUBIChanging(value);
					this.SendPropertyChanging();
					this._DireccionUBI = value;
					this.SendPropertyChanged("DireccionUBI");
					this.OnDireccionUBIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidad", DbType="VarChar(50)")]
		public string Localidad
		{
			get
			{
				return this._Localidad;
			}
			set
			{
				if ((this._Localidad != value))
				{
					this.OnLocalidadChanging(value);
					this.SendPropertyChanging();
					this._Localidad = value;
					this.SendPropertyChanged("Localidad");
					this.OnLocalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroContacto", DbType="VarChar(50)")]
		public string nroContacto
		{
			get
			{
				return this._nroContacto;
			}
			set
			{
				if ((this._nroContacto != value))
				{
					this.OnnroContactoChanging(value);
					this.SendPropertyChanging();
					this._nroContacto = value;
					this.SendPropertyChanged("nroContacto");
					this.OnnroContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="VarChar(50)")]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this.OnCorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._CorreoElectronico = value;
					this.SendPropertyChanged("CorreoElectronico");
					this.OnCorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Torganizacion_TAdministrador", Storage="_TAdministrador", ThisKey="IdOrganizacion", OtherKey="IdOrganizacion")]
		public EntitySet<TAdministrador> TAdministrador
		{
			get
			{
				return this._TAdministrador;
			}
			set
			{
				this._TAdministrador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Torganizacion_TSolicitud", Storage="_TSolicitud", ThisKey="IdOrganizacion", OtherKey="IdOrganizacion")]
		public EntitySet<TSolicitud> TSolicitud
		{
			get
			{
				return this._TSolicitud;
			}
			set
			{
				this._TSolicitud.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAdministrador(TAdministrador entity)
		{
			this.SendPropertyChanging();
			entity.Torganizacion = this;
		}
		
		private void detach_TAdministrador(TAdministrador entity)
		{
			this.SendPropertyChanging();
			entity.Torganizacion = null;
		}
		
		private void attach_TSolicitud(TSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.Torganizacion = this;
		}
		
		private void detach_TSolicitud(TSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.Torganizacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TSolicitud")]
	public partial class TSolicitud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSolicitud;
		
		private System.Nullable<int> _IdOrganizacion;
		
		private System.Nullable<int> _IdMascota;
		
		private System.Nullable<int> _IdAdoptante;
		
		private string _codigo;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaSolicitud;
		
		private string _Descripcion;
		
		private EntityRef<TAdoptante> _TAdoptante;
		
		private EntityRef<TMascota> _TMascota;
		
		private EntityRef<Torganizacion> _Torganizacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSolicitudChanging(int value);
    partial void OnIdSolicitudChanged();
    partial void OnIdOrganizacionChanging(System.Nullable<int> value);
    partial void OnIdOrganizacionChanged();
    partial void OnIdMascotaChanging(System.Nullable<int> value);
    partial void OnIdMascotaChanged();
    partial void OnIdAdoptanteChanging(System.Nullable<int> value);
    partial void OnIdAdoptanteChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnFechaSolicitudChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaSolicitudChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public TSolicitud()
		{
			this._TAdoptante = default(EntityRef<TAdoptante>);
			this._TMascota = default(EntityRef<TMascota>);
			this._Torganizacion = default(EntityRef<Torganizacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSolicitud", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSolicitud
		{
			get
			{
				return this._IdSolicitud;
			}
			set
			{
				if ((this._IdSolicitud != value))
				{
					this.OnIdSolicitudChanging(value);
					this.SendPropertyChanging();
					this._IdSolicitud = value;
					this.SendPropertyChanged("IdSolicitud");
					this.OnIdSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrganizacion", DbType="Int")]
		public System.Nullable<int> IdOrganizacion
		{
			get
			{
				return this._IdOrganizacion;
			}
			set
			{
				if ((this._IdOrganizacion != value))
				{
					if (this._Torganizacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdOrganizacionChanging(value);
					this.SendPropertyChanging();
					this._IdOrganizacion = value;
					this.SendPropertyChanged("IdOrganizacion");
					this.OnIdOrganizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMascota", DbType="Int")]
		public System.Nullable<int> IdMascota
		{
			get
			{
				return this._IdMascota;
			}
			set
			{
				if ((this._IdMascota != value))
				{
					if (this._TMascota.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMascotaChanging(value);
					this.SendPropertyChanging();
					this._IdMascota = value;
					this.SendPropertyChanged("IdMascota");
					this.OnIdMascotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdoptante", DbType="Int")]
		public System.Nullable<int> IdAdoptante
		{
			get
			{
				return this._IdAdoptante;
			}
			set
			{
				if ((this._IdAdoptante != value))
				{
					if (this._TAdoptante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAdoptanteChanging(value);
					this.SendPropertyChanging();
					this._IdAdoptante = value;
					this.SendPropertyChanged("IdAdoptante");
					this.OnIdAdoptanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(20)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSolicitud", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaSolicitud
		{
			get
			{
				return this._FechaSolicitud;
			}
			set
			{
				if ((this._FechaSolicitud != value))
				{
					this.OnFechaSolicitudChanging(value);
					this.SendPropertyChanging();
					this._FechaSolicitud = value;
					this.SendPropertyChanged("FechaSolicitud");
					this.OnFechaSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAdoptante_TSolicitud", Storage="_TAdoptante", ThisKey="IdAdoptante", OtherKey="IdAdoptante", IsForeignKey=true)]
		public TAdoptante TAdoptante
		{
			get
			{
				return this._TAdoptante.Entity;
			}
			set
			{
				TAdoptante previousValue = this._TAdoptante.Entity;
				if (((previousValue != value) 
							|| (this._TAdoptante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAdoptante.Entity = null;
						previousValue.TSolicitud.Remove(this);
					}
					this._TAdoptante.Entity = value;
					if ((value != null))
					{
						value.TSolicitud.Add(this);
						this._IdAdoptante = value.IdAdoptante;
					}
					else
					{
						this._IdAdoptante = default(Nullable<int>);
					}
					this.SendPropertyChanged("TAdoptante");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TMascota_TSolicitud", Storage="_TMascota", ThisKey="IdMascota", OtherKey="IdMascota", IsForeignKey=true)]
		public TMascota TMascota
		{
			get
			{
				return this._TMascota.Entity;
			}
			set
			{
				TMascota previousValue = this._TMascota.Entity;
				if (((previousValue != value) 
							|| (this._TMascota.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TMascota.Entity = null;
						previousValue.TSolicitud.Remove(this);
					}
					this._TMascota.Entity = value;
					if ((value != null))
					{
						value.TSolicitud.Add(this);
						this._IdMascota = value.IdMascota;
					}
					else
					{
						this._IdMascota = default(Nullable<int>);
					}
					this.SendPropertyChanged("TMascota");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Torganizacion_TSolicitud", Storage="_Torganizacion", ThisKey="IdOrganizacion", OtherKey="IdOrganizacion", IsForeignKey=true)]
		public Torganizacion Torganizacion
		{
			get
			{
				return this._Torganizacion.Entity;
			}
			set
			{
				Torganizacion previousValue = this._Torganizacion.Entity;
				if (((previousValue != value) 
							|| (this._Torganizacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Torganizacion.Entity = null;
						previousValue.TSolicitud.Remove(this);
					}
					this._Torganizacion.Entity = value;
					if ((value != null))
					{
						value.TSolicitud.Add(this);
						this._IdOrganizacion = value.IdOrganizacion;
					}
					else
					{
						this._IdOrganizacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Torganizacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class TUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Usuario;
		
		private System.Data.Linq.Binary _Contrasena;
		
		private EntitySet<TAdministrador> _TAdministrador;
		
		private EntitySet<TAdoptante> _TAdoptante;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasenaChanging(System.Data.Linq.Binary value);
    partial void OnContrasenaChanged();
    #endregion
		
		public TUsuario()
		{
			this._TAdministrador = new EntitySet<TAdministrador>(new Action<TAdministrador>(this.attach_TAdministrador), new Action<TAdministrador>(this.detach_TAdministrador));
			this._TAdoptante = new EntitySet<TAdoptante>(new Action<TAdoptante>(this.attach_TAdoptante), new Action<TAdoptante>(this.detach_TAdoptante));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarBinary(200)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TAdministrador", Storage="_TAdministrador", ThisKey="Usuario", OtherKey="Usuario")]
		public EntitySet<TAdministrador> TAdministrador
		{
			get
			{
				return this._TAdministrador;
			}
			set
			{
				this._TAdministrador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TAdoptante", Storage="_TAdoptante", ThisKey="Usuario", OtherKey="Usuario")]
		public EntitySet<TAdoptante> TAdoptante
		{
			get
			{
				return this._TAdoptante;
			}
			set
			{
				this._TAdoptante.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAdministrador(TAdministrador entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = this;
		}
		
		private void detach_TAdministrador(TAdministrador entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = null;
		}
		
		private void attach_TAdoptante(TAdoptante entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = this;
		}
		
		private void detach_TAdoptante(TAdoptante entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = null;
		}
	}
	
	public partial class spActualizarMascotaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spActualizarMascotaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spActualizarOrganizacionResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spActualizarOrganizacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(38) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spActualizarProductoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spActualizarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarAdministradorResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarAdministradorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(22) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarAdoptanteResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarAdoptanteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarMascotaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarMascotaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarOrganizacionResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarOrganizacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarSolicitudResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarSolicitudResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spCambiarEstadoSolicitudResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spCambiarEstadoSolicitudResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEditarAdministradorResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEditarAdministradorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarAdministradorResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarAdministradorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(37) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarAdoptanteResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarAdoptanteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarMascotaResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarMascotaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spEliminarOrganizacionResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spEliminarOrganizacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spListarAdministradorResult
	{
		
		private int _IdAdministrador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _nroCelular;
		
		private string _TipoDocumento;
		
		private string _nroDocumento;
		
		private string _Usuario;
		
		private System.Nullable<int> _IdOrganizacion;
		
		public spListarAdministradorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdministrador", DbType="Int NOT NULL")]
		public int IdAdministrador
		{
			get
			{
				return this._IdAdministrador;
			}
			set
			{
				if ((this._IdAdministrador != value))
				{
					this._IdAdministrador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroCelular", DbType="VarChar(9)")]
		public string nroCelular
		{
			get
			{
				return this._nroCelular;
			}
			set
			{
				if ((this._nroCelular != value))
				{
					this._nroCelular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(50)")]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this._TipoDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDocumento", DbType="VarChar(50)")]
		public string nroDocumento
		{
			get
			{
				return this._nroDocumento;
			}
			set
			{
				if ((this._nroDocumento != value))
				{
					this._nroDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrganizacion", DbType="Int")]
		public System.Nullable<int> IdOrganizacion
		{
			get
			{
				return this._IdOrganizacion;
			}
			set
			{
				if ((this._IdOrganizacion != value))
				{
					this._IdOrganizacion = value;
				}
			}
		}
	}
	
	public partial class spListarAdoptanteResult
	{
		
		private int _IdAdoptante;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<System.DateTime> _Fecha_Nacimiento;
		
		private string _TipoDocumento;
		
		private string _nroDocumento;
		
		private string _nroCelular;
		
		private string _Direccion;
		
		private string _Estado_civil;
		
		private string _Ocupacion;
		
		public spListarAdoptanteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAdoptante", DbType="Int NOT NULL")]
		public int IdAdoptante
		{
			get
			{
				return this._IdAdoptante;
			}
			set
			{
				if ((this._IdAdoptante != value))
				{
					this._IdAdoptante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocumento", DbType="VarChar(50)")]
		public string TipoDocumento
		{
			get
			{
				return this._TipoDocumento;
			}
			set
			{
				if ((this._TipoDocumento != value))
				{
					this._TipoDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDocumento", DbType="VarChar(10)")]
		public string nroDocumento
		{
			get
			{
				return this._nroDocumento;
			}
			set
			{
				if ((this._nroDocumento != value))
				{
					this._nroDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroCelular", DbType="VarChar(9)")]
		public string nroCelular
		{
			get
			{
				return this._nroCelular;
			}
			set
			{
				if ((this._nroCelular != value))
				{
					this._nroCelular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_civil", DbType="VarChar(50)")]
		public string Estado_civil
		{
			get
			{
				return this._Estado_civil;
			}
			set
			{
				if ((this._Estado_civil != value))
				{
					this._Estado_civil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ocupacion", DbType="VarChar(50)")]
		public string Ocupacion
		{
			get
			{
				return this._Ocupacion;
			}
			set
			{
				if ((this._Ocupacion != value))
				{
					this._Ocupacion = value;
				}
			}
		}
	}
	
	public partial class spLoginUsuarioResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spLoginUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(50)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
